import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = { title: "Privacy Policy | Nayizameen" };

export default function PrivacyPolicyPage() {
  return <><Navbar /><main className="min-h-screen bg-slate-50"><section className="bg-primary-800 py-14 text-white"><div className="mx-auto max-w-4xl px-4 md:px-6"><p className="text-sm font-semibold tracking-wider text-primary-100">LEGAL</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">Privacy Policy</h1><p className="mt-3 text-primary-100">Last updated: September 10, 2026</p></div></section><article className="mx-auto max-w-4xl space-y-8 px-4 py-12 text-slate-600 md:px-6"><PolicySection title="Information we collect">We collect information you provide when you create an account, post a listing, contact another user, or communicate with us. This can include your name, email address, phone number, property details, and listing images.</PolicySection><PolicySection title="How we use information">We use this information to operate the platform, display your listings, connect property seekers with owners or agents, respond to enquiries, improve our services, and help keep the platform secure.</PolicySection><PolicySection title="Sharing information">Your listing details and the contact information you choose to provide may be visible to other users. We do not sell your personal information. We may share information where required by law or to protect users and the platform.</PolicySection><PolicySection title="Cookies and local storage">Nayizameen may use browser storage and similar technologies to keep you signed in, remember preferences, and support listing functionality.</PolicySection><PolicySection title="Your choices">You can update account details and manage your listings through your profile. To request help with your data, contact us at info@nayizameen.com.</PolicySection></article></main><Footer /></>;
}

function PolicySection({ title, children }) { return <section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-100 md:p-8"><h2 className="text-xl font-bold text-slate-900">{title}</h2><p className="mt-4 leading-7">{children}</p></section>; }