export const lahoreSocieties = {
  A: ["Aabpara Coop Housing Society", "Abdalians Cooperative Housing Society", "Abdullah Town", "Abid City", "Abuzar Housing Scheme", "Adams Housing Scheme", "Aftab Garden", "Agrics Town", "Ahmad Avenue", "Ahmad Housing Society", "AIMC Residential Colony", "Airline Housing Society", "Aitchison Society", "Akram Abad", "Al Hafeez Gardens", "Al Hamra Town", "Al Haram City", "Al Haram Garden", "Al Jalil Garden", "Al Jannat Homes", "Al Jannat Housing Scheme", "Al Kareem Garden", "Al Madina Avenue", "Al Noor Park Housing Society", "Al Rahim Homes", "Al Raziq Garden", "Al-Hadi Garden", "Al-Amin Housing Society", "Al-Ghani Garden", "Al-Hadi Garden", "Al-Hamd Gardens", "Al-Kareem Premier Housing Scheme", "Al-Mava Housing Scheme", "Al-Noor Orchard", "Al-Qayyum Garden", "Al-Rehmat Housing", "Al-Wahab Garden - Phase 1", "Al Park", "Al Town", "Al View Garden", "Alia Town", "Allama Iqbal Town", "Alpha Society", "Aman Town", "Amina Park", "Angoori Bagh Scheme 1", "Angoori Bagh Scheme 1 - Block A", "Anwar Town", "Architects Engineers Housing Society", "Arya Nagar", "Ashiana-e-Quaid Housing Scheme", "Ashrafi Town", "Askari 10", "Askari 11", "Askari 11", "Askari 9", "Atomic Energy Society - PAEC", "Avicenna City", "Awami Colony", "Awan Town", "Awasi Housing Society", "Azam Gardens", "Azizia Town", "Awan Town"],
  B: ["Badduke", "Bagh Gul Begum", "Bagh-e-Iram Housing Society", "Bahar Colony", "Bahria Education & Medical City", "Bahria Nasheman", "Bahria Nasheman - Iris", "Bahria Nasheman - Sunflower", "Bahria Nasheman - Zinia", "Bahria Orchard", "Bahria Town", "Bahria Town - Overseas Enclave", "Bandian Wala", "Bankers Avenue Cooperative Housing Society", "Bankers Co-operative Housing Society", "Barkat Market", "Bata Officer Colony", "Beacon House Society", "Bhatti Colony", "Bilal Gunj", "Bismillah Housing Scheme", "BOR - Board of Revenue Housing Society"],
  C: ["Canal Burg", "Canal Fort II", "Canal Garden", "Canal Park", "Canal Valley", "Canal View", "Cavalry Ground", "Cavalry Ground", "Central Park Housing Scheme", "Chahal Homes", "Chaburji Quarters", "Chaudhary Colony", "China Scheme", "Chinar Bagh", "Chinar Court", "Christian Colony", "Civil Defence", "CMA Colony", "Combo Colony", "Cricketer Villas"],
  D: ["Dawood Residency Housing Scheme", "DHA 11 Rahbar Sector 5 (KEMC)", "DHA 9 Town", "DHA Defence", "Dilkusha Gardens", "Divine Gardens", "Divine Homes", "Doctors Housing Society", "Dream Avenue Lahore", "Dream Gardens", "Dream Housing Society", "Dream Villas"],
  E: ["Eden Avenue", "Eden Avenue Extension", "Eden Canal Villas", "Eden City", "Eden Cottage 1", "Eden Cottages 2", "Eden Defence Villas", "Eden Gardens", "Eden Gardens Extension", "Eden Lane Villas 1", "Eden Lane Villas 2", "Eden Palace Villas", "Eden Park", "Eden Residencia", "Eden Value Homes", "Eden Villas", "Edenabad Extension", "Edenabad Extension 1", "Education Town", "Elite Town", "EME Society", "Etihad Town", "Evergreen Housing Scheme", "Excise & Taxation Housing Scheme"],
  F: ["Faisal Town", "Farid Kot House", "Farooq Avenue", "Fazaia Housing Scheme", "Fazlia Colony", "Firdous Colony", "Formanites Housing Scheme", "Fort Villas"],
};
export const cityDirectoryTabs = ["A - F", "G - L", "M - R", "S - Z"];

