"use client";

import Image from "next/image";
import Link from "next/link";
import { Building2, Eye, EyeOff, FileText, LockKeyhole, Mail, MapPin, Phone, ShieldCheck, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

function Field({ label, icon: Icon, children }) {
  return <label className="block"><span className="mb-2 block text-sm font-medium text-gray-700">{label}</span><span className="relative block"><Icon className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />{children}</span></label>;
}

export default function RegisterPage() {
  const router = useRouter();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmation, setShowConfirmation] = useState(false);
  const [accountType, setAccountType] = useState("user");
  const [verificationDocuments, setVerificationDocuments] = useState([]);
  const [message, setMessage] = useState("");
  const input = "h-12 w-full rounded-xl border border-gray-200 pl-11 pr-4 text-sm outline-none transition focus:border-primary-700 focus:ring-4 focus:ring-primary-50";
  const submit = async (event) => { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: values.get("fullName"), email: values.get("email"), phone: values.get("phone"), password: values.get("password"), passwordConfirmation: values.get("passwordConfirmation"), accountType }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "Unable to create your account."); return; } window.localStorage.setItem("nayizameen-session", JSON.stringify(data.user)); setMessage("Account created. Opening your profile..."); window.setTimeout(() => router.push("/profile"), 700); };
  const handleDocuments = (event) => { setVerificationDocuments(Array.from(event.target.files || [])); };

  return <main className="grid min-h-screen bg-white lg:grid-cols-2">
    <section className="relative hidden overflow-hidden bg-primary-800 p-12 text-white lg:flex lg:flex-col"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(0,151,179,0.5),_transparent_50%)]" /><Link href="/" className="relative z-10 flex items-center gap-3"><Image src="/logo-horizontal.png" alt="Nayizameen" width={173} height={25} className="h-9 w-auto brightness-0 invert" /><span className="border-l border-white/30 pl-3 text-sm font-medium text-primary-100">Property Portal</span></Link><div className="relative z-10 my-auto max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-semibold tracking-wider text-primary-100"><ShieldCheck className="h-4 w-4" /> VERIFIED LISTINGS</span><h1 className="mt-6 text-5xl font-bold leading-tight">Find a place to call home.</h1><p className="mt-5 text-lg leading-8 text-primary-100">Create your free account to save favourite properties, connect with verified agents, and discover your next move.</p><div className="mt-10 space-y-4">{["Save properties and searches", "Get alerts for new listings", "Manage your property enquiries"].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-medium"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-white/10"><MapPin className="h-4 w-4 text-primary-100" /></span>{item}</div>)}</div></div><p className="relative z-10 text-sm text-primary-200">(c) 2026 Nayizameen. All rights reserved.</p></section>
    <section className="flex items-center justify-center px-4 py-10 sm:px-8"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex items-center gap-2 lg:hidden"><Image src="/logo-horizontal.png" alt="Nayizameen" width={173} height={25} className="h-9 w-auto" /></Link><p className="text-sm font-semibold tracking-wider text-primary-700">GET STARTED</p><h2 className="mt-2 text-3xl font-bold text-gray-900">Create an account</h2><p className="mt-3 text-sm leading-6 text-gray-500">Join Nayizameen and make your property search easier.</p>
      <form onSubmit={submit} className="mt-7 space-y-4">
        <fieldset><legend className="mb-2 block text-sm font-medium text-gray-700">Register as</legend><div className="grid grid-cols-2 gap-3"><label className={`cursor-pointer rounded-xl border p-3 transition ${accountType === "user" ? "border-primary-700 bg-primary-50 ring-2 ring-primary-100" : "border-gray-200"}`}><input type="radio" name="accountType" value="user" checked={accountType === "user"} onChange={() => setAccountType("user")} className="sr-only" /><span className="flex items-center gap-2 text-sm font-semibold text-gray-800"><UserRound className="h-4 w-4 text-primary-700" /> Property seeker</span><span className="mt-1 block text-xs text-gray-500">Save and manage properties</span></label><label className={`cursor-pointer rounded-xl border p-3 transition ${accountType === "agent" ? "border-primary-700 bg-primary-50 ring-2 ring-primary-100" : "border-gray-200"}`}><input type="radio" name="accountType" value="agent" checked={accountType === "agent"} onChange={() => setAccountType("agent")} className="sr-only" /><span className="flex items-center gap-2 text-sm font-semibold text-gray-800"><Building2 className="h-4 w-4 text-primary-700" /> Register as an agent</span><span className="mt-1 block text-xs text-gray-500">Apply to list your agency</span></label></div></fieldset>
        <Field label="Full name" icon={UserRound}><input required name="fullName" placeholder="Your full name" className={input} /></Field>
        <Field label="Email address" icon={Mail}><input type="email" required name="email" placeholder="you@example.com" className={input} /></Field>
        <Field label="Phone number (optional)" icon={Phone}><input type="tel" name="phone" placeholder="+92 300 0000000" className={input} /></Field>
        {accountType === "agent" && <div className="space-y-4 rounded-2xl border border-primary-100 bg-primary-50/60 p-4"><div><p className="text-sm font-semibold text-primary-800">Agency information</p><p className="mt-1 text-xs leading-5 text-gray-500">These details will be reviewed before your agent profile is approved.</p></div><Field label="Agency name" icon={Building2}><input required name="agencyName" placeholder="Your registered agency name" className={input + " bg-white"} /></Field><Field label="Agency registration number" icon={FileText}><input required name="agencyRegistrationNumber" placeholder="e.g. REG-123456" className={input + " bg-white"} /></Field><Field label="Agency contact number" icon={Phone}><input required type="tel" name="agencyContactNumber" placeholder="+92 300 0000000" className={input + " bg-white"} /></Field><label className="block"><span className="mb-2 block text-sm font-medium text-gray-700">Agency address</span><textarea required name="agencyAddress" rows="3" placeholder="Complete registered agency address" className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm outline-none transition focus:border-primary-700 focus:ring-4 focus:ring-primary-50" /></label><label className="block"><span className="mb-2 block text-sm font-medium text-gray-700">Government verification documents</span><span className="flex cursor-pointer items-start gap-3 rounded-xl border border-dashed border-primary-200 bg-white px-4 py-3"><FileText className="mt-1 h-5 w-5 shrink-0 text-primary-700" /><span className="min-w-0 flex-1"><input required multiple name="verificationDocuments" type="file" accept="image/jpeg,image/png,application/pdf" onChange={handleDocuments} className="block w-full text-xs text-gray-500 file:mr-3 file:rounded-lg file:border-0 file:bg-primary-50 file:px-3 file:py-2 file:text-xs file:font-semibold file:text-primary-700" /><span className="mt-1 block text-xs text-gray-400">Upload registration certificate or official proof. PDF, JPG, PNG.</span></span></span>{verificationDocuments.length > 0 && <span className="mt-2 block text-xs font-medium text-primary-700">{verificationDocuments.length} document{verificationDocuments.length === 1 ? "" : "s"} selected</span>}</label></div>}
        <Field label="Password" icon={LockKeyhole}><span className="relative block"><input type={showPassword ? "text" : "password"} required minLength={8} name="password" placeholder="At least 8 characters" className={input + " pr-11"} /><button type="button" onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 p-1.5 text-gray-400" aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></span></Field>
        <Field label="Confirm password" icon={LockKeyhole}><span className="relative block"><input type={showConfirmation ? "text" : "password"} required minLength={8} name="passwordConfirmation" placeholder="Repeat your password" className={input + " pr-11"} /><button type="button" onClick={() => setShowConfirmation((value) => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 p-1.5 text-gray-400" aria-label={showConfirmation ? "Hide password confirmation" : "Show password confirmation"}>{showConfirmation ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></span></Field>
        <label className="flex items-start gap-2 pt-1 text-sm leading-5 text-gray-600"><input type="checkbox" required className="mt-0.5 h-4 w-4 accent-primary-700" />I agree to the <button type="button" onClick={() => setMessage("Terms and privacy details will be available once authentication is connected.")} className="font-medium text-primary-700 hover:underline">terms and privacy policy</button>.</label>
        <button type="submit" className="h-12 w-full rounded-xl bg-primary-700 text-sm font-semibold text-white shadow-lg shadow-primary-700/20 transition hover:bg-primary-800">{accountType === "agent" ? "Submit agent application" : "Create account"}</button>
      </form>
      {message && <p role="status" className="mt-5 rounded-xl border border-primary-100 bg-primary-50 px-4 py-3 text-sm text-primary-800">{message}</p>}<p className="mt-7 text-center text-sm text-gray-500">Already have an account? <Link href="/login" className="font-semibold text-primary-700 hover:underline">Sign in</Link></p><p className="mt-6 text-center text-sm"><Link href="/" className="font-medium text-gray-600 hover:text-primary-700">Back to homepage</Link></p></div></section>
  </main>;
}


